server:
  port: 8503

spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    username: haydikodlayalim
    password: haydikodlayalim
  cloud:
    stream:
      bindings:
        input:
          destination: msqueue
eureka:
  client:
    instance:
      hostname: ${EUREKA_SERVER_HOST:localhost}
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}


management:
  endpoints:
    web:
      exposure:
        include: "*"